name: CI

on: [ push, pull_request ]

env:
  PROJECT_NAME: zint  
  REPORT_EMAIL: roque@code-intelligence.com

jobs:
  fuzz_ean_fuzzer:
    runs-on: ubuntu-latest
    steps:
      - id: start-fuzzing
        name: Build And Start Fuzzing
        uses: CodeIntelligenceTesting/github-actions/start-fuzzing@master
        with:
          cognito_user: ${{ secrets.COGNITO_USER }}
          cognito_password: ${{ secrets.COGNITO_PASSWORD }}
          project: ${{ env.PROJECT_NAME }}
          test_collection: "ean_fuzzer"          
          report_email: ${{ env.REPORT_EMAIL }}
      - id: monitor-fuzzing
        name: Monitor Fuzzing
        uses: CodeIntelligenceTesting/github-actions/monitor-fuzzing@master
        with:
          cognito_user: ${{ secrets.COGNITO_USER }}
          cognito_password: ${{ secrets.COGNITO_PASSWORD }}
          project: ${{ env.PROJECT_NAME }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          timeout: 30
      - id: report-coverage
        name: Report Coverage
        uses: CodeIntelligenceTesting/github-actions/report-coverage@master
        if: ${{ github.event_name == 'pull_request' && (success() || failure()) }}
        with:
          cognito_user: ${{ secrets.COGNITO_USER }}
          cognito_password: ${{ secrets.COGNITO_PASSWORD }}
          project: ${{ env.PROJECT_NAME }}
          test_collection: "ean_fuzzer"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          commit: ${{ github.sha }}
          
